services:
  rednote2tg:
    #    build: .
    image: ghcr.io/pokedo0/rednote2tg:latest
    pull_policy: always
    container_name: rednote2tg
    restart: unless-stopped
    working_dir: /app
    environment:
      TZ: Asia/Shanghai
      NODE_PATH: /app/node_modules
    volumes:
      - ./config/config.yaml:/app/config/config.yaml
      - ./data:/app/data
      - ./logs:/app/logs
